using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using CyberSourceMergedSpec.Core;
using CyberSourceMergedSpec.Core.Exceptions;
using CyberSourceMergedSpec.Core.Models;
using CyberSourceMergedSpec.Core.Request;
using CyberSourceMergedSpec.Core.Response;
using CyberSourceMergedSpec.Errors;
using CyberSourceMergedSpec.Models;

namespace CyberSourceMergedSpec.Api;

/// <summary>
/// REST API for the Decision Manager Service
/// </summary>
public sealed class DecisionManager
{
    private readonly RawClient _rawClient;
    private readonly Server _server;

    internal DecisionManager(RawClient rawClient, Server server)
    {
        _rawClient = rawClient;
        _server = server;
    }

    /// <summary>
    /// Take action on a DM post-transactional case
    /// </summary>
    /// <param name="id">An unique identification number generated by Cybersource to identify the submitted request.</param>
    /// <param name="caseManagementActionsRequest"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="ActionDecisionManagerCaseResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="ActionDecisionManagerCaseError"/> when the server returns an error response.</exception>
    public Task<ActionDecisionManagerCaseResponse> ActionDecisionManagerCase(string id,
        CaseManagementActionsRequest caseManagementActionsRequest,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/risk/v1/decisions/{id}/actions"),
            [new TemplateParam("id", id)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(caseManagementActionsRequest),
            JsonResponse.Create<ActionDecisionManagerCaseResponse>(),
            ActionDecisionManagerCaseErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// This call adds/deletes/converts the request information in the negative list.
    /// <para>
    /// Provide the list to be updated as the path parameter. This value can be 'postiive', 'negative' or 'review'.
    /// </para>
    /// </summary>
    /// <param name="type">The list to be updated. It can be 'positive', 'negative' or 'review'.</param>
    /// <param name="addNegativeListRequest"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="AddNegativeError"/> when the server returns an error response.</exception>
    public Task AddNegative(string type,
        AddNegativeListRequest addNegativeListRequest,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/risk/v1/lists/{type}/entries"),
            [new TemplateParam("type", type)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(addNegativeListRequest),
            VoidResponse.Instance,
            AddNegativeErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Add a comment to a DM post-transactional case
    /// </summary>
    /// <param name="id">An unique identification number generated by Cybersource to identify the submitted request.</param>
    /// <param name="caseManagementCommentsRequest"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="CommentDecisionManagerCaseResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="CommentDecisionManagerCaseError"/> when the server returns an error response.</exception>
    public Task<CommentDecisionManagerCaseResponse> CommentDecisionManagerCase(string id,
        CaseManagementCommentsRequest caseManagementCommentsRequest,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/risk/v1/decisions/{id}/comments"),
            [new TemplateParam("id", id)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(caseManagementCommentsRequest),
            JsonResponse.Create<CommentDecisionManagerCaseResponse>(),
            CommentDecisionManagerCaseErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// Decision Manager can help you automate and streamline your fraud operations. Decision Manager will return a decision based on the request values.
    /// </summary>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="CreateBundledDecisionManagerCaseError"/> when the server returns an error response.</exception>
    public Task CreateBundledDecisionManagerCase(RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/risk/v1/decisions"),
            [],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            EmptyBody.Instance,
            VoidResponse.Instance,
            CreateBundledDecisionManagerCaseErrorResponse.Instance,
            [],
            requestOptions,
            ct);

    /// <summary>
    /// This can be used to -
    /// 1. Add known fraudulent data to the fraud history
    /// 2. Remove data added to history with Transaction Marking Tool or by uploading chargeback files
    /// 3. Remove chargeback data from history that was automatically added.
    /// For detailed information, contact your Cybersource representative
    /// <para>
    /// Place the request ID of the transaction you want to mark as suspect (or remove from history) as the path parameter in this request.
    /// </para>
    /// </summary>
    /// <param name="id">Request ID of the transaction that you want to mark as suspect or remove from history.</param>
    /// <param name="fraudMarkingActionRequest"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="FraudUpdateError"/> when the server returns an error response.</exception>
    public Task FraudUpdate(string id,
        FraudMarkingActionRequest fraudMarkingActionRequest,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/risk/v1/decisions/{id}/marking"),
            [new TemplateParam("id", id)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(fraudMarkingActionRequest),
            VoidResponse.Instance,
            FraudUpdateErrorResponse.Instance,
            [],
            requestOptions,
            ct);
}
