using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ClientReferenceInformation2
{
    /// <summary>
    /// Merchant-generated order reference or tracking number. It is recommended that you send a unique value for each
    /// transaction so that you can perform meaningful searches for the transaction.
    /// <para>
    /// #### Used by
    /// <b>Authorization</b>
    /// Required field.
    /// </para>
    /// <para>
    /// #### PIN Debit
    /// Requests for PIN debit reversals need to use the same merchant reference number that was used in the transaction that is being
    /// reversed.
    /// </para>
    /// <para>
    /// Required field for all PIN Debit requests (purchase, credit, and reversal).
    /// </para>
    /// <para>
    /// #### FDC Nashville Global
    /// Certain circumstances can cause the processor to truncate this value to 15 or 17 characters for Level II and Level III processing, which can cause a discrepancy between the value you submit and the value included in some processor reports.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("code")]
    [MaxLength(59)]
    public string? Code { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("partner")]
    public Partner1? Partner { get; init; }

    /// <summary>
    /// The name of the Connection Method client (such as Virtual Terminal or SOAP Toolkit API) that the merchant uses to send a transaction request to CyberSource.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applicationName")]
    public string? ApplicationName { get; init; }

    /// <summary>
    /// Version of the CyberSource application or integration used for a transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applicationVersion")]
    public string? ApplicationVersion { get; init; }

    /// <summary>
    /// The entity that is responsible for running the transaction and submitting the processing request to CyberSource. This could be a person, a system, or a connection method.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applicationUser")]
    public string? ApplicationUser { get; init; }

    /// <summary>
    /// Identifier that you assign to the transaction. Normally generated by a client server to identify a unique API request.
    /// <para>
    /// <b>Note</b> Use this field only if you want to support merchant-initiated reversal and void operations.
    /// </para>
    /// <para>
    /// #### Used by
    /// <b>Authorization, Authorization Reversal, Capture, Credit, and Void</b>
    /// Optional field.
    /// </para>
    /// <para>
    /// #### PIN Debit
    /// For a PIN debit reversal, your request must include a request ID or a merchant transaction identifier.
    /// Optional field for PIN debit purchase or credit requests.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(30)]
    public string? TransactionId { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
