using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ConsumerAuthenticationInformation2
{
    /// <summary>
    /// Payer authentication transaction identifier passed to link the validation and authorization calls.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationTransactionContextId")]
    [MaxLength(30)]
    public string? AuthenticationTransactionContextId { get; init; }

    /// <summary>
    /// Unique identifier generated by the card-issuing bank for Visa, American Express, JCB, Diners Club, and
    /// Discover transactions after the customer is authenticated. The value is in base64. When you
    /// request the card authorization service, CyberSource automatically converts the value, not the field name,
    /// to the format required by your payment processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cavv")]
    [MaxLength(255)]
    public string? Cavv { get; init; }

    /// <summary>
    /// Web based token used to authenticate consumer with Rupay authentication provider.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionToken")]
    [MaxLength(256)]
    public string? TransactionToken { get; init; }

    /// <summary>
    /// Transaction identifier generated by CyberSource for successful enrollment or validation checks.
    /// Use this value, which is in base64, to match an outgoing PAReq with an incoming PARes.
    /// CyberSource forwards the XID with the card authorization service to these payment processors in these cases:
    /// - Barclays
    /// - Streamline (when the <b>ecommerceIndicator</b><c>=spa</c>)
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("xid")]
    public string? Xid { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
