using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ConsumerAuthenticationInformation10
{
    /// <summary>
    /// Identifies the UI Type the ACS will use to complete the challenge. <b>NOTE</b>: Only available for App transactions using the Cardinal Mobile SDK.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsRenderingType")]
    public string? AcsRenderingType { get; init; }

    /// <summary>
    /// Unique identifier assigned by the EMVCo Secretariat upon Testing and Approval.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsReferenceNumber")]
    [MaxLength(50)]
    public string? AcsReferenceNumber { get; init; }

    /// <summary>
    /// Unique transaction identifier assigned by the ACS to identify a single transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsTransactionId")]
    [MaxLength(36)]
    public string? AcsTransactionId { get; init; }

    /// <summary>
    /// Directory Server assigned ACS identifier.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsOperatorID")]
    public string? AcsOperatorId { get; init; }

    /// <summary>
    /// Raw authentication data that comes from the cardissuing bank. Primary authentication field that
    /// indicates if authentication was successful and if liability shift occurred. You should examine first the
    /// result of this field. This field contains one of these values:
    /// - <c>-1</c>: Invalid PARes.
    /// - <c>0</c>: Successful validation.
    /// - <c>1</c>: Cardholder is not participating, but the attempt to authenticate was recorded.
    /// - <c>6</c>: Issuer unable to perform authentication.
    /// - <c>9</c>: Cardholder did not complete authentication.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationResult")]
    public string? AuthenticationResult { get; init; }

    /// <summary>
    /// Indicates the type of authentication that will be used to challenge the card holder.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// 01 - Static
    /// </para>
    /// <para>
    /// 02 - Dynamic
    /// </para>
    /// <para>
    /// 03 - OOB (Out of Band)
    /// </para>
    /// <para>
    /// 04 - Decoupled
    /// </para>
    /// <para>
    /// 20 - OTP hosted at merchant end. (Rupay S2S flow)
    /// <b>NOTE</b>:  EMV 3-D Secure version 2.1.0 supports values 01-03.  Version 2.2.0 supports values 01-04.  Decoupled authentication is not supported at this time.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationType")]
    [MaxLength(2)]
    public string? AuthenticationType { get; init; }

    /// <summary>
    /// Message that explains the authenticationResult reply field.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationStatusMsg")]
    public string? AuthenticationStatusMsg { get; init; }

    /// <summary>
    /// Payer authentication transaction identifier is used to link the check
    /// enrollment and validate authentication messages. For Rupay, this field should be passed as request only for Resend OTP use case.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationTransactionId")]
    [MaxLength(26)]
    public string? AuthenticationTransactionId { get; init; }

    /// <summary>
    /// Payer authentication transaction identifier passed to link the validation and authorization calls.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationTransactionContextId")]
    [MaxLength(30)]
    public string? AuthenticationTransactionContextId { get; init; }

    /// <summary>
    /// Web based token used to authenticate consumer with Rupay authentication provider.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionToken")]
    [MaxLength(256)]
    public string? TransactionToken { get; init; }

    /// <summary>
    /// The Base64 encoded JSON Payload of CB specific Authorization Values returned in the challenge Flow
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authorizationPayload")]
    public string? AuthorizationPayload { get; init; }

    /// <summary>
    /// Unique identifier generated by the card-issuing bank for Visa, American Express, JCB, Diners Club, and
    /// Discover transactions after the customer is authenticated. The value is in base64. When you
    /// request the card authorization service, CyberSource automatically converts the value, not the field name,
    /// to the format required by your payment processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cavv")]
    [MaxLength(255)]
    public string? Cavv { get; init; }

    /// <summary>
    /// Field that is returned only when the CAVV is generated, which occurs when paresStatus
    /// contains the values Y (successful authentication) or A (attempted authentication). If
    /// you use the ATOS processor, send the value of this field in the <c>cavv_algorithm</c> request field of the
    /// authorization service. This field contains one of these values:
    /// - <c>2</c>: Visa, American Express, JCB, Diners Club, and Discover
    /// - <c>3</c>: Mastercard
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cavvAlgorithm")]
    [MaxLength(1)]
    public string? CavvAlgorithm { get; init; }

    /// <summary>
    /// An indicator as to why the transaction was canceled.
    /// Possible Values:
    /// <list type="bullet">
    ///   <item><description><c>01</c>: Cardholder selected Cancel.</description></item>
    ///   <item><description><c>02</c>: Reserved for future EMVCo use (values invalid until defined by EMVCo).</description></item>
    ///   <item><description><c>03</c>: Transaction Timed Out—Decoupled Authentication</description></item>
    ///   <item><description><c>04</c>: Transaction timed out at ACS—other timeouts</description></item>
    ///   <item><description><c>05</c>: Transaction Timed out at ACS - First CReq not received by ACS</description></item>
    ///   <item><description><c>06</c>: Transaction Error</description></item>
    ///   <item><description><c>07</c>: Unknown</description></item>
    ///   <item><description><c>08</c>: Transaction Timed Out at SDK</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("challengeCancelCode")]
    [MaxLength(2)]
    public string? ChallengeCancelCode { get; init; }

    /// <summary>
    /// The directory server error code indicating a problem with this transaction. Note - Max Length of this field is typically 3 characters.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("directoryServerErrorCode")]
    public string? DirectoryServerErrorCode { get; init; }

    /// <summary>
    /// Directory server text and additional detail about the error for this transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("directoryServerErrorDescription")]
    [MaxLength(4096)]
    public string? DirectoryServerErrorDescription { get; init; }

    /// <summary>
    /// This field describes the type of 3DS transaction flow that took place.  It can be one of three possible flows;
    /// CH - Challenge
    /// FR - Frictionless
    /// FD - Frictionless with delegation, (challenge not generated by the issuer but by the scheme on behalf of the issuer).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("effectiveAuthenticationType")]
    [MaxLength(2)]
    public string? EffectiveAuthenticationType { get; init; }

    /// <summary>
    /// Indicator used to differentiate Internet transactions from other types. The authentication failed if this field
    /// is not returned. For Visa, if your payment processor is Streamline, Barclays, AIBMS, or FDC Germany,
    /// you receive the value vbv_failure instead of internet when eci is 07.
    /// The value of this field is passed automatically to the authorization service if you request the services
    /// together. This field contains one of these values:
    /// - <c>aesk</c>: American Express SafeKey authentication verified successfully.
    /// - <c>aesk_attempted</c>: Card not enrolled in American Express SafeKey, but the attempt to authenticate was recorded.
    /// - <c>dipb</c>: Discover ProtectBuy authentication verified successfully.
    /// - <c>dipb_attempted</c>: Card not enrolled in Discover ProtectBuy, but the attempt to authenticate was recorded.
    /// - <c>internet</c>: Authentication was not verified successfully.
    /// - <c>js</c>: J/Secure authentication verified successfully.
    /// - <c>js_attempted</c>: Card not enrolled in J/Secure, but the attempt to authenticate was recorded.
    /// - <c>moto</c>: Mail or telephone order.
    /// - <c>pb_attempted</c>: Card not enrolled in Diners Club ProtectBuy, but the attempt to authenticate was recorded.
    /// - <c>recurring</c>: Recurring transaction.
    /// - <c>spa</c>: Mastercard Identity Check authentication verified successfully.
    /// - <c>spa_failure</c>: Mastercard Identity Check failed authentication.
    /// - <c>vbv</c>: Visa Secure authentication verified successfully.
    /// - <c>vbv_attempted</c>: Card not enrolled in Visa Secure, but the attempt to authenticate was recorded.
    /// - <c>vbv_failure</c>: Visa Secure authentication unavailable.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("indicator")]
    public string? Indicator { get; init; }

    /// <summary>
    /// Indicates the number of authentication cycles attempted by the cardholder and is tracked by the Issuing Banks ACS.Example: if customer gets the challenge window and enter in their one time password and hit submit then that interaction counter should just be 1.
    /// When customer gets the challenge window and the bank asks if they want to have the one time password  sent to their phone or their email and they have to choose before going to the next screen to enter in their one time password then this interaction count would be 2.
    /// One for the selection of how they want the one time password delivered and another with them actually entering in the one time password and hitting the submit button.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("interactionCounter")]
    [MaxLength(2)]
    public string? InteractionCounter { get; init; }

    /// <summary>
    /// Note This field applies only to non-U.S-issued cards.
    /// <para>
    /// For enroll, Numeric electronic commerce indicator (ECI) returned only for Visa, American Express, JCB,
    /// Diners Club, and Discover transactions when the card is not enrolled. For more information, see
    /// "Interpreting the Reply," page 22.
    /// </para>
    /// <para>
    /// If you are not using the CyberSource payment services, you must send this value to your payment
    /// processor in the subsequent request for card authorization. This field contains one of these values:
    /// - <c>06</c>: The card can be enrolled. Liability shift.
    /// - <c>07</c>: The card cannot be enrolled. No liability shift.
    /// </para>
    /// <para>
    /// For validate, Numeric electronic commerce indicator (ECI) returned only for Visa, American Express, JCB,
    /// Diners Club, and Discover transactions. The field is absent when authentication fails.
    /// You must send this value to your payment processor in the subsequent request for card authorization.
    /// This field contains one of these values:
    /// - <c>05</c>: Successful authentication
    /// - <c>06</c>: Authentication attempted
    /// - <c>07</c>: Failed authentication (No response from the merchant because of a problem.)
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eci")]
    public string? Eci { get; init; }

    /// <summary>
    /// ECI value that can be returned for Visa, Mastercard, American Express, JCB, Diners Club, and Discover.
    /// The field is absent when authentication fails. If your payment processor is Streamline, you must pass the
    /// value of this field instead of the value of <c>eci</c> or <c>ucafCollectionIndicator</c>.
    /// <para>
    /// This field can contain one of these values:
    /// - <c>01</c>: Authentication attempted (Mastercard)
    /// - <c>02</c>: Successful authentication (Mastercard)
    /// - <c>05</c>: Successful authentication (Visa, American Express, JCB, Diners Club, and Discover)
    /// - <c>06</c>: Authentication attempted (Visa, American Express, JCB, Diners Club, and Discover)
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eciRaw")]
    public string? EciRaw { get; init; }

    /// <summary>
    /// Raw result of the authentication check. If you are configured for Asia, Middle East, and Africa Gateway
    /// Processing, you need to send the value of this field in your authorization request. This field can contain
    /// one of these values:
    /// - <c>A</c>: Proof of authentication attempt was generated.
    /// - <c>N</c>: Customer failed or canceled authentication. Transaction denied.
    /// - <c>U</c>: Authentication not completed regardless of the reason.
    /// - <c>Y</c>: Customer was successfully authenticated.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paresStatus")]
    public string? ParesStatus { get; init; }

    /// <summary>
    /// SDK unique transaction identifier that is generated on each new transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sdkTransactionId")]
    [MaxLength(36)]
    public string? SdkTransactionId { get; init; }

    /// <summary>
    /// This field contains the 3D Secure version that was used to process the transaction. For example: 2.2.0
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("specificationVersion")]
    public string? SpecificationVersion { get; init; }

    /// <summary>
    /// Unique transaction identifier assigned by the 3DS Server to identify a single transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("threeDSServerTransactionId")]
    [MaxLength(36)]
    public string? ThreeDsServerTransactionId { get; init; }

    /// <summary>
    /// AAV is a unique identifier generated by the card-issuing bank for Mastercard Identity Check
    /// transactions after the customer is authenticated. The value is in base64.
    /// Include the data in the card authorization request.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("ucafAuthenticationData")]
    public string? UcafAuthenticationData { get; init; }

    /// <summary>
    /// For enroll, Returned only for Mastercard transactions. Indicates that authentication is not required because the
    /// customer is not enrolled. Add the value of this field to the authorization field ucaf_collection_indicator.
    /// This field can contain these values: 0, 1.
    /// <para>
    /// For validate, Numeric electronic commerce indicator (ECI) returned only for Mastercard Identity Check
    /// transactions. The field is absent when authentication fails. You must send this value to your payment
    /// processor in the request for card authorization. This field contain one of these values:
    /// - <c>0</c>: Authentication data not collected, and customer authentication was not completed.
    /// - <c>1</c>: Authentication data not collected because customer authentication was not completed.
    /// - <c>2</c>: Authentication data collected because customer completed authentication.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("ucafCollectionIndicator")]
    public string? UcafCollectionIndicator { get; init; }

    /// <summary>
    /// Enables the communication of trusted beneficiary/whitelist status between the ACS, the DS and the 3DS Requestor.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// Y - 3DS Requestor is whitelisted by cardholder
    /// </para>
    /// <para>
    /// N - 3DS Requestor is not whitelisted by cardholder
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("whiteListStatus")]
    [MaxLength(1)]
    public string? WhiteListStatus { get; init; }

    /// <summary>
    /// This data element will be populated by the system setting Whitelist Status. Possible Values: 01 - 3DS/ Server/ 02 – DS/03 - ACS
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("whiteListStatusSource")]
    [MaxLength(2)]
    public string? WhiteListStatusSource { get; init; }

    /// <summary>
    /// Transaction identifier generated by CyberSource for successful enrollment or validation checks.
    /// Use this value, which is in base64, to match an outgoing PAReq with an incoming PARes.
    /// CyberSource forwards the XID with the card authorization service to these payment processors in these cases:
    /// - Barclays
    /// - Streamline (when the <b>ecommerceIndicator</b><c>=spa</c>)
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("xid")]
    public string? Xid { get; init; }

    /// <summary>
    /// The Directory Server Transaction ID is generated by the Mastercard Directory Server during the authentication transaction and passed back to the merchant with the authentication results.
    /// For Cybersource Through Visanet Gateway:
    /// The value for this field corresponds to the following data in the TC 33 capture file3: Record: CP01 TCR7, Position: 114-149, Field: MC AVV Verification—Directory Server Transaction ID
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("directoryServerTransactionId")]
    [MaxLength(36)]
    public string? DirectoryServerTransactionId { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
