using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ConsumerAuthenticationInformation
{
    /// <summary>
    /// Cardholder authentication verification value (CAVV).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cavv")]
    [MaxLength(40)]
    public string? Cavv { get; init; }

    /// <summary>
    /// This field details out the type of transaction. Below are the possible values.
    /// 08:GC- Guest Checkout.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionFlowIndicator")]
    [MaxLength(2)]
    public string? TransactionFlowIndicator { get; init; }

    /// <summary>
    /// Algorithm used to generate the CAVV for Visa Secure or the UCAF authentication data for Mastercard Identity Check.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cavvAlgorithm")]
    [MaxLength(1)]
    public string? CavvAlgorithm { get; init; }

    /// <summary>
    /// Raw electronic commerce indicator (ECI).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eciRaw")]
    [MaxLength(2)]
    public string? EciRaw { get; init; }

    /// <summary>
    /// Payer authentication response status.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paresStatus")]
    [MaxLength(1)]
    public string? ParesStatus { get; init; }

    /// <summary>
    /// Verification response enrollment status.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("veresEnrolled")]
    [MaxLength(1)]
    public string? VeresEnrolled { get; init; }

    /// <summary>
    /// Transaction identifier.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("xid")]
    [MaxLength(40)]
    public string? Xid { get; init; }

    /// <summary>
    /// Universal cardholder authentication field (UCAF) collection indicator.
    /// <para>
    /// #### CyberSource through VisaNet
    /// The value for this field corresponds to the following data in the TC 33 capture file5:
    /// - Record: CP01 TCR7
    /// - Position: 5
    /// - Field: Mastercard Electronic Commerce Indicators—UCAF Collection Indicator
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("ucafCollectionIndicator")]
    [MaxLength(1)]
    public string? UcafCollectionIndicator { get; init; }

    /// <summary>
    /// Universal cardholder authentication field (UCAF) data.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("ucafAuthenticationData")]
    [MaxLength(32)]
    public string? UcafAuthenticationData { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("strongAuthentication")]
    public StrongAuthentication? StrongAuthentication { get; init; }

    /// <summary>
    /// The Directory Server Transaction ID is generated by the Mastercard Directory Server during the authentication transaction and passed back to the merchant with the authentication results.
    /// For Cybersource Through Visanet Gateway:
    /// The value for this field corresponds to the following data in the TC 33 capture file3:
    /// Record: CP01 TCR7, Position: 114-149, Field: MC AVV Verification—Directory Server Transaction ID
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("directoryServerTransactionId")]
    [MaxLength(36)]
    public string? DirectoryServerTransactionId { get; init; }

    /// <summary>
    /// This field contains 3DS version that was used for Secured Consumer Authentication (SCA).
    /// The value for this field should be in the format major.minor.patch version.
    /// <para>
    /// Valid Values are:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>2.1.0</c> (EMV 3D Secure Version 2.1)</description></item>
    ///   <item><description><c>2.2.0</c> (EMV 3D Secure Version 2.2)</description></item>
    ///   <item><description><c>2.3.0</c> (EMV 3D Secure Version 2.3)</description></item>
    ///   <item><description><c>2.4.0</c> (EMV 3D Secure Version 2.4)</description></item>
    ///   <item><description><c>2.5.0</c> (EMV 3D Secure Version 2.5)</description></item>
    ///   <item><description><c>2.6.0</c> (EMV 3D Secure Version 2.6)</description></item>
    ///   <item><description><c>2.7.0</c> (EMV 3D Secure Version 2.7)</description></item>
    ///   <item><description><c>2.8.0</c> (EMV 3D Secure Version 2.8)</description></item>
    ///   <item><description><c>2.9.0</c> (EMV 3D Secure Version 2.9)</description></item>
    /// </list>
    /// <para>
    /// For Visa Platform Connect:
    /// The value for this field corresponds to the following data in the TC 33 capture file3:
    /// Record: CP01 TCR7, Position: 113 , Field: MC AVV Verification—Program Protocol
    /// </para>
    /// <para>
    /// It will contain one of the following values:
    /// - <c>1</c> (3D Secure Version 1.x (3DS 1.0))
    /// - <c>2</c> (EMV 3-D Secure (3DS 2.x))
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paSpecificationVersion")]
    [MaxLength(20)]
    public string? PaSpecificationVersion { get; init; }

    /// <summary>
    /// Indicates the type of authentication that will be used to challenge the card holder.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// 01 - Static
    /// </para>
    /// <para>
    /// 02 - Dynamic
    /// </para>
    /// <para>
    /// 03 - OOB (Out of Band)
    /// </para>
    /// <para>
    /// 04 - Decoupled
    /// </para>
    /// <para>
    /// 20 - OTP hosted at merchant end. (Rupay S2S flow)
    /// <b>NOTE</b>:  EMV 3-D Secure version 2.1.0 supports values 01-03.  Version 2.2.0 supports values 01-04.  Decoupled authentication is not supported at this time.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationType")]
    [MaxLength(2)]
    public string? AuthenticationType { get; init; }

    /// <summary>
    /// JWT returned by the 3D Secure provider when the authentication is complete. Required for Hybrid integration if you use the Cybersource-generated access token. Note: Max. length of this field is 2048 characters.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseAccessToken")]
    public string? ResponseAccessToken { get; init; }

    /// <summary>
    /// Unique transaction identifier assigned by the ACS to identify a single transaction.
    /// <para>
    /// This field is supported for Cartes Bancaires Fast'R transactions on Credit Mutuel-CIC.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsTransactionId")]
    [MaxLength(36)]
    public string? AcsTransactionId { get; init; }

    /// <summary>
    /// An override field that a merchant can pass in to set the challenge window size to display to the end cardholder.  The ACS (Active Control Server) will reply with content that is formatted appropriately to this window size to allow for the best user experience.  The sizes are width x height in pixels of the window displayed in the cardholder browser window.
    /// <para>
    /// 01 - 250x400
    /// </para>
    /// <para>
    /// 02 - 390x400
    /// </para>
    /// <para>
    /// 03 - 500x600
    /// </para>
    /// <para>
    /// 04 - 600x400
    /// </para>
    /// <para>
    /// 05 - Full page
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsWindowSize")]
    [MaxLength(2)]
    public string? AcsWindowSize { get; init; }

    /// <summary>
    /// Data that documents and supports a specific authentication process.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("alternateAuthenticationData")]
    [MaxLength(2048)]
    public string? AlternateAuthenticationData { get; init; }

    /// <summary>
    /// Date and time in UTC of the cardholder authentication. Format: YYYYMMDDHHMM
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("alternateAuthenticationDate")]
    [MaxLength(14)]
    public string? AlternateAuthenticationDate { get; init; }

    /// <summary>
    /// Mechanism used by the cardholder to authenticate to the 3D Secure requestor.
    /// Possible values:
    /// - <c>01</c>: No authentication occurred
    /// - <c>02</c>: Login using merchant system credentials
    /// - <c>03</c>: Login using Federated ID
    /// - <c>04</c>: Login using issuer credentials
    /// - <c>05</c>: Login using third-party authenticator
    /// - <c>06</c>: Login using FIDO Authenticator
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("alternateAuthenticationMethod")]
    public string? AlternateAuthenticationMethod { get; init; }

    /// <summary>
    /// The date/time of the authentication at the 3DS servers. RISK update authorization service in auth request
    /// payload with value returned in <c>consumerAuthenticationInformation.alternateAuthenticationData</c> if merchant calls via CYBS or field can be
    /// provided by merchant in authorization request if calling an external 3DS provider.
    /// <para>
    /// This field is supported for Cartes Bancaires Fast'R transactions on Credit Mutuel-CIC.
    /// Format: YYYYMMDDHHMMSS
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationDate")]
    [MaxLength(14)]
    public string? AuthenticationDate { get; init; }

    /// <summary>
    /// Payer authentication transaction identifier passed to link the check enrollment
    /// and validate authentication messages.For Rupay,this is passed only in Re-Send OTP usecase.
    /// <b>Note</b>: Required for Standard integration, Rupay Seamless server to server integration for enroll service.
    /// Required for Hybrid integration for validate service.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationTransactionId")]
    [MaxLength(26)]
    public string? AuthenticationTransactionId { get; init; }

    /// <summary>
    /// An indicator as to why the transaction was canceled.
    /// Possible Values:
    /// <list type="bullet">
    ///   <item><description><c>01</c>: Cardholder selected Cancel.</description></item>
    ///   <item><description><c>02</c>: Reserved for future EMVCo use (values invalid until defined by EMVCo).</description></item>
    ///   <item><description><c>03</c>: Transaction Timed Out—Decoupled Authentication</description></item>
    ///   <item><description><c>04</c>: Transaction timed out at ACS—other timeouts</description></item>
    ///   <item><description><c>05</c>: Transaction Timed out at ACS - First CReq not received by ACS</description></item>
    ///   <item><description><c>06</c>: Transaction Error</description></item>
    ///   <item><description><c>07</c>: Unknown</description></item>
    ///   <item><description><c>08</c>: Transaction Timed Out at SDK</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("challengeCancelCode")]
    [MaxLength(2)]
    public string? ChallengeCancelCode { get; init; }

    /// <summary>
    /// Possible values:
    /// - <c>01</c>: No preference
    /// - <c>02</c>: No challenge request
    /// - <c>03</c>: Challenge requested (3D Secure requestor preference)
    /// - <c>04</c>: Challenge requested (mandate)
    /// - <c>05</c>: No challenge requested (transactional risk analysis is already performed)
    /// - <c>06</c>: No challenge requested (Data share only)
    /// - <c>07</c>: No challenge requested (strong consumer authentication is already performed)
    /// - <c>08</c>: No challenge requested (utilize whitelist exemption if no challenge required)
    /// - <c>09</c>: Challenge requested (whitelist prompt requested if challenge required)
    /// <b>Note</b> This field will default to <c>01</c> on merchant configuration and can be overridden by the merchant.
    /// EMV 3D Secure version 2.1.0 supports values <c>01-04</c>. Version 2.2.0 supports values <c>01-09</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("challengeCode")]
    public string? ChallengeCode { get; init; }

    /// <summary>
    /// The <c>consumerAuthenticationInformation.challengeCode</c> indicates the authentication type/level, or challenge, that was presented to the cardholder
    /// at checkout by the merchant when calling the Carte Bancaire 3DS servers via CYBS RISK services. It conveys to
    /// the issuer the alternative authentication methods that the consumer used.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("challengeStatus")]
    [MaxLength(2)]
    public string? ChallengeStatus { get; init; }

    /// <summary>
    /// An alias that uniquely identifies the customer's account and credit card on file.
    /// Note This field is required if Tokenization is enabled in the merchant profile settings.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customerCardAlias")]
    [MaxLength(128)]
    public string? CustomerCardAlias { get; init; }

    /// <summary>
    /// Indicates whether the 3DS Requestor requests the ACS to utilize Decoupled Authentication and agrees to utilize Decoupled Authentication if the ACS confirms its use.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// Y - Decoupled Authentication is supported and preferred if challenge is necessary
    /// </para>
    /// <para>
    /// N - Do not use Decoupled Authentication
    /// </para>
    /// <para>
    /// <b>Default Value</b>: N
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("decoupledAuthenticationIndicator")]
    [MaxLength(1)]
    public string? DecoupledAuthenticationIndicator { get; init; }

    /// <summary>
    /// Indicates the maximum amount of time that the 3DS Requestor will wait for an ACS (Active control server) to provide the results of a Decoupled Authentication transaction (in minutes).
    /// Possible Values: Numeric values between 1 and 10080 accepted.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("decoupledAuthenticationMaxTime")]
    [MaxLength(5)]
    public string? DecoupledAuthenticationMaxTime { get; init; }

    /// <summary>
    /// Indicates that the card being used is the one designated as the primary payment card for purchase.
    /// Recommended for Discover ProtectBuy.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("defaultCard")]
    public bool? DefaultCard { get; init; }

    /// <summary>
    /// Determines the channel that the transaction came through. Possible Values: SDK/Browser/3RI. 3RI - 3DS request initiated.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("deviceChannel")]
    [MaxLength(10)]
    public string? DeviceChannel { get; init; }

    /// <summary>
    /// An integer value greater than 1 indicating the max number of permitted authorizations for installment payments.
    /// <b>Note</b> This is required if the merchant and cardholder have agreed to installment payments.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("installmentTotalCount")]
    public int? InstallmentTotalCount { get; init; }

    /// <summary>
    /// Calculated by merchants as per PSD2<b> RTS</b> (EEA** card fraud divided by all EEA card volumes).
    /// Possible Values:
    /// 1 = Represents fraud rate &lt;=1
    /// <para>
    /// 2 = Represents fraud rate &gt;1 and &lt;=6
    /// </para>
    /// <para>
    /// 3 = Represents fraud rate &gt;6 and &lt;=13
    /// </para>
    /// <para>
    /// 4 = Represents fraud rate &gt;13 and &lt;=25
    /// </para>
    /// <para>
    /// 5 = Represents fraud rate &gt;25
    /// </para>
    /// <para>
    /// EEA** = European Economic Area
    /// RTS** = Regulatory Technical Standards
    /// PSD2** = Payment Services Directive
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantFraudRate")]
    [MaxLength(2)]
    public string? MerchantFraudRate { get; init; }

    /// <summary>
    /// Indicates whether the customer has opted in for marketing offers.
    /// Recommended for Discover ProtectBuy.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("marketingOptIn")]
    public bool? MarketingOptIn { get; init; }

    /// <summary>
    /// Indicates origin of the marketing offer. Recommended for Discover ProtectBuy.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("marketingSource")]
    [MaxLength(40)]
    public string? MarketingSource { get; init; }

    /// <summary>
    /// Merchant category code.
    /// <b>Important</b> Required only for Visa Secure transactions in Brazil.
    /// Do not use this request field for any other types of transactions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("mcc")]
    [MaxLength(4)]
    public string? Mcc { get; init; }

    /// <summary>
    /// Risk Score provided by merchants. This is specific for CB transactions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantScore")]
    public int? MerchantScore { get; init; }

    /// <summary>
    /// Category of the message for a specific use case. Possible values:
    /// <list type="bullet">
    ///   <item><description><c>01</c>: PA- payment authentication</description></item>
    ///   <item><description><c>02</c>: NPA- non-payment authentication</description></item>
    ///   <item><description><c>03-79</c>: Reserved for EMVCo future use (values invalid until defined by EMVCo)</description></item>
    ///   <item><description><c>80-99</c>: Reserved for DS use</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("messageCategory")]
    public string? MessageCategory { get; init; }

    /// <summary>
    /// The global score calculated by the CB scoring platform and returned to merchants.
    /// <para>
    /// Possible values:
    /// - '00' - '99'
    /// </para>
    /// <para>
    /// When you request the payer authentication and authorization services separately, get the value for this field from the pa_network_score reply field.
    /// </para>
    /// <para>
    /// This field is supported only for Cartes Bancaires Fast'R transactions on Credit Mutuel-CIC.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("networkScore")]
    [MaxLength(2)]
    public string? NetworkScore { get; init; }

    /// <summary>
    /// Non-Payer Authentication Indicator.
    /// Possible values:
    /// - <c>01</c>: Add card
    /// - <c>02</c>: Maintain card information
    /// - <c>03</c>: Cardholder verification for EMV token
    /// - <c>04-80</c> Reserved for EMVCo
    /// - <c>80-90</c> Reserved DS
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("npaCode")]
    [MaxLength(2)]
    public string? NpaCode { get; init; }

    /// <summary>
    /// Specifies the Brazilian payment account type used for the transaction.
    /// This field overrides other payment types that might be specified in the request.
    /// Use one of the following values for this field:
    /// - <c>NA</c>: Not applicable. Do not override other payment types that are specified in the request.
    /// - <c>CR</c>: Credit card.
    /// - <c>DB</c>: Debit card.
    /// - <c>VSAVR</c>: Visa Vale Refeicao
    /// - <c>VSAVA</c>: Visa Vale Alimentacao
    /// <b>Important</b> Required only for Visa Secure transactions in Brazil.
    /// Do not use this request field for any other types of transactions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("overridePaymentMethod")]
    public string? OverridePaymentMethod { get; init; }

    /// <summary>
    /// Two-character <see href="https://developer.cybersource.com/library/documentation/sbc/quickref/countries_alpha_list.pdf">ISO Standard Country Codes</see>..
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("overrideCountryCode")]
    [MaxLength(2)]
    public string? OverrideCountryCode { get; init; }

    /// <summary>
    /// This field carry data that the ACS can use to verify the authentication process.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priorAuthenticationData")]
    [MaxLength(2048)]
    public string? PriorAuthenticationData { get; init; }

    /// <summary>
    /// Mechanism used by the Cardholder to previously authenticate to the 3DS Requestor.
    /// <para>
    /// 01 - Frictionless authentication occurred by ACS
    /// </para>
    /// <para>
    /// 02 - Cardholder challenge occurred by ACS
    /// </para>
    /// <para>
    /// 03 - AVS verified
    /// </para>
    /// <para>
    /// 04 - Other issuer methods
    /// </para>
    /// <para>
    /// 05-79 - Reserved for EMVCo future use (values invalid until defined by EMVCo)
    /// </para>
    /// <para>
    /// 80-99 - Reserved for DS use
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priorAuthenticationMethod")]
    [MaxLength(2)]
    public string? PriorAuthenticationMethod { get; init; }

    /// <summary>
    /// This data element contains a ACS Transaction ID for a prior authenticated transaction.
    /// For example, the first recurring transaction that was authenticated with the cardholder
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priorAuthenticationReferenceId")]
    [MaxLength(36)]
    public string? PriorAuthenticationReferenceId { get; init; }

    /// <summary>
    /// Date and time in UTC of the prior cardholder authentication. Format – YYYYMMDDHHMM
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priorAuthenticationTime")]
    [MaxLength(12)]
    public string? PriorAuthenticationTime { get; init; }

    /// <summary>
    /// Specifies the product code, which designates the type of transaction.
    /// Specify one of the following values for this field:
    /// - AIR: Airline purchase
    /// Important Required for American Express SafeKey (U.S.).
    /// - <c>ACC</c>: Accommodation Rental
    /// - <c>ACF</c>: Account funding
    /// - <c>CHA</c>: Check acceptance
    /// - <c>DIG</c>: Digital Goods
    /// - <c>DSP</c>: Cash Dispensing
    /// - <c>GAS</c>: Fuel
    /// - <c>GEN</c>: General Retail
    /// - <c>LUX</c>: Luxury Retail
    /// - <c>PAL</c>: Prepaid activation and load
    /// - <c>PHY</c>: Goods or services purchase
    /// - <c>QCT</c>: Quasi-cash transaction
    /// - <c>REN</c>: Car Rental
    /// - <c>RES</c>: Restaurant
    /// - <c>SVC</c>: Services
    /// - <c>TBD</c>: Other
    /// - <c>TRA</c>: Travel
    /// <b>Important</b> Required for Visa Secure transactions in Brazil.
    /// Do not use this request field for any other types of transactions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("productCode")]
    [MaxLength(3)]
    public string? ProductCode { get; init; }

    /// <summary>
    /// The URL of the merchant’s return page. CyberSource adds this return URL to the step-up JWT and returns it in the
    /// response of the Payer Authentication enrollment call. The merchant's return URL page serves as a listening URL.
    /// Once the bank session completes, the merchant receives a POST to their URL. This response contains the completed
    /// bank session’s transactionId. The merchant’s return page should capture the transaction ID and send it in the
    /// Payer Authentication validation call.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("returnUrl")]
    [MaxLength(2048)]
    public string? ReturnUrl { get; init; }

    /// <summary>
    /// Cardinal's directory server assigned 3DS Requestor ID value
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("requestorId")]
    [MaxLength(35)]
    public string? RequestorId { get; init; }

    /// <summary>
    /// Indicates the type of 3RI request.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// 01 - Recurring transaction
    /// </para>
    /// <para>
    /// 02 - Installment transaction
    /// </para>
    /// <para>
    /// 03 - Add card
    /// </para>
    /// <para>
    /// 04 - Maintain card
    /// </para>
    /// <para>
    /// 05 - Account verification
    /// </para>
    /// <para>
    /// 06 - Split/delayed shipment
    /// </para>
    /// <para>
    /// 07 - Top-up
    /// </para>
    /// <para>
    /// 08 - Mail Order
    /// </para>
    /// <para>
    /// 09 - Telephone Order
    /// </para>
    /// <para>
    /// 10 - Whitelist status check
    /// </para>
    /// <para>
    /// 11 - Other payment
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("requestorInitiatedAuthenticationIndicator")]
    [MaxLength(2)]
    public string? RequestorInitiatedAuthenticationIndicator { get; init; }

    /// <summary>
    /// Cardinal's directory server assigned 3DS Requestor Name value
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("requestorName")]
    [MaxLength(40)]
    public string? RequestorName { get; init; }

    /// <summary>
    /// Reference ID that corresponds to the device fingerprinting data that was collected previously.
    /// Note Required for Hybrid integration.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("referenceId")]
    [MaxLength(50)]
    public string? ReferenceId { get; init; }

    /// <summary>
    /// This field indicates the maximum amount of time for all 3DS 2.0 messages to be communicated between all components (in minutes).
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// Greater than or equal to 05 (05 is the minimum timeout to set)
    /// </para>
    /// <para>
    /// Cardinal Default is set to 15
    /// </para>
    /// <para>
    /// NOTE: This field is a required 3DS 2.0 field and Cardinal sends in a default of 15 if nothing is passed
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sdkMaxTimeout")]
    [MaxLength(2)]
    public string? SdkMaxTimeout { get; init; }

    /// <summary>
    /// Indicates dedicated payment processes and procedures were used, potential secure corporate payment exemption applies.
    /// Possible Values : 0/1
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("secureCorporatePaymentIndicator")]
    [MaxLength(1)]
    public string? SecureCorporatePaymentIndicator { get; init; }

    /// <summary>
    /// Transaction mode identifier. Identifies the channel from which the transaction originates.
    /// Possible values:
    /// <list type="bullet">
    ///   <item><description><c>M</c>: MOTO (Mail Order Telephone Order)</description></item>
    ///   <item><description><c>R</c>: Retail</description></item>
    ///   <item><description><c>S</c>: eCommerce</description></item>
    ///   <item><description><c>P</c>: Mobile Device</description></item>
    ///   <item><description><c>T</c>: Tablet</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionMode")]
    public string? TransactionMode { get; init; }

    /// <summary>
    /// Enables the communication of trusted beneficiary/whitelist status between the ACS, the DS and the 3DS Requestor.
    /// <para>
    /// Possible Values:
    /// </para>
    /// <para>
    /// Y - 3DS Requestor is whitelisted by cardholder
    /// </para>
    /// <para>
    /// N - 3DS Requestor is not whitelisted by cardholder
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("whiteListStatus")]
    [MaxLength(1)]
    public string? WhiteListStatus { get; init; }

    /// <summary>
    /// Indicates which directory server was used while authentication process, this data is useful in case of scenarios
    /// when domestic scheme directory server is not present and authentication fallbacks to global scheme directory server.
    /// Possible values:
    /// - VISA - Returned for Mada VISA Co-badged cards, when authentication falls back to VISA Directory Server
    /// - MASTERCARD - Returned for Mada MasterCard Co-badged cards, when authentication falls back to MasterCard Directory Server
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authenticationBrand")]
    [MaxLength(16)]
    public string? AuthenticationBrand { get; init; }

    /// <summary>
    /// This field describes the type of 3DS transaction flow that took place.  It can be one of three possible flows;
    /// CH - Challenge
    /// FR - Frictionless
    /// FD - Frictionless with delegation, (challenge not generated by the issuer but by the scheme on behalf of the issuer).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("effectiveAuthenticationType")]
    [MaxLength(2)]
    public string? EffectiveAuthenticationType { get; init; }

    /// <summary>
    /// Provides additional information as to why the PAResStatus has a specific value.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("signedParesStatusReason")]
    [MaxLength(2)]
    public string? SignedParesStatusReason { get; init; }

    /// <summary>
    /// Payer authentication result (PARes) message returned by the card-issuing bank.
    /// If you need to show proof of enrollment checking, you may need to
    /// decrypt and parse the string for the information required by the payment card company.
    /// For more information, see "Storing Payer Authentication Data," page 160.
    /// Important The value is in base64. You must remove all carriage returns and line feeds before
    /// adding the PARes to the request.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("signedPares")]
    public string? SignedPares { get; init; }

    /// <summary>
    /// Unique identifier assigned by the EMVCo Secretariat upon Testing and Approval.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acsReferenceNumber")]
    [MaxLength(50)]
    public string? AcsReferenceNumber { get; init; }

    /// <summary>
    /// EMVCo-assigned unique identifier. This field is required in Cardholder Initiated 3DS fully authenticated mada transactions.
    /// When you request the payer authentication and authorization services separately, get the value for this field from the payerAuthEnrollReply_dsReferenceNumber or payerAuthValidateReply_dsReferenceNumber response field.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dsReferenceNumber")]
    [MaxLength(32)]
    public string? DsReferenceNumber { get; init; }

    /// <summary>
    /// Risk Assessment from Mastercard. This is to be sent by merchant if they would like to request a score
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("scoreRequest")]
    public int? ScoreRequest { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
