using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record Mandate1
{
    /// <summary>
    /// Unique value generated by CyberSource that identifies the transaction. Use this value to identify transactions in the Collections Report, which provides settlement
    /// information.
    /// <para>
    /// For details, see the <c>direct_debit_reconciliation_reference_number</c> reply field description in <see href="https://apps.cybersource.com/library/documentation/dev_guides/Ingenico_ePayments_Dev/html/">Ingenico ePayments Developer Guide For Direct Debits.</see>
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("referenceNumber")]
    public string? ReferenceNumber { get; init; }

    /// <summary>
    /// Whether the direct debit is the first or last direct debit associated with the mandate, or one in between.
    /// Required only for the United Kingdom.
    /// Possible values:
    /// - <c>001</c>: First direct debit associated with this mandate. Use this value if a one-time direct debit).
    /// - <c>002</c>: Subsequent direct debits associated with this mandate.
    /// - <c>003</c>: Last direct debit associated with this mandate.
    /// <para>
    /// For details, see the <c>direct_debit_recurring_type</c> request field description in <see href="https://apps.cybersource.com/library/documentation/dev_guides/Ingenico_ePayments_Dev/html/">Ingenico ePayments Developer Guide For Direct Debits.</see>
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("recurringType")]
    public string? RecurringType { get; init; }

    /// <summary>
    /// The mandate ID. Required only for the United Kingdom.
    /// <para>
    /// For details, see the <c>mandate_id</c> request field description in <see href="https://apps.cybersource.com/library/documentation/dev_guides/Ingenico_ePayments_Dev/html/">Ingenico ePayments Developer Guide For Direct Debits.</see>
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
