using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record MerchantInformation25
{
    /// <summary>
    /// An unique identification number generated by Cybersource to identify the submitted request. Returned by all services.
    /// It is also appended to the endpoint of the resource.
    /// On incremental authorizations, this value with be the same as the identification number returned in the original authorization response.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("resellerId")]
    [MaxLength(26)]
    public string? ResellerId { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
