using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record PayoutsOptions1
{
    /// <summary>
    /// This field contains a number that is used with other data elements as a key to identify and track all messages related to a given cardholder transaction; that is, to a given transaction set.
    /// <para>
    /// Recommended format: ydddhhnnnnnn
    /// </para>
    /// <para>
    /// Positions 1-4: The yddd equivalent of the date, where y = 0-9 and ddd = 001 – 366.
    /// Positions 5-12: A unique identification number generated by the merchant.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(12)]
    public string? RetrievalReferenceNumber { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
