using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record PayoutsOptions
{
    /// <summary>
    /// This field identifies the card acceptor for defining the point of service terminal in both local and interchange environments. An acquirer-assigned code identifying the card acceptor for the transaction.
    /// Depending on the acquirer and merchant billing and reporting requirements, the code can represent a merchant, a specific merchant location, or a specific merchant location terminal.
    /// Acquiring Institution Identification Code uniquely identifies the merchant.
    /// The value from the original is required in any subsequent messages, including reversals, chargebacks, and representments.
    /// * Applicable only for CTV for Payouts.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acquirerMerchantId")]
    [MaxLength(15)]
    public string? AcquirerMerchantId { get; init; }

    /// <summary>
    /// This code identifies the financial institution acting as the acquirer of this customer transaction. The acquirer is the member or system user that signed the merchant or ADM or dispensed cash.
    /// This number is usually Visa-assigned.
    /// * Applicable only for CTV for Payouts.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("acquirerBin")]
    [MaxLength(11)]
    public string? AcquirerBin { get; init; }

    /// <summary>
    /// This field contains a number that is used with other data elements as a key to identify and track all messages related to a given cardholder transaction;
    /// that is, to a given transaction set.
    /// <para>
    /// Format:
    ///   Positions 1-4: The <c>yddd</c> equivalent of the date, where <c>y</c> = 0-9 and <c>ddd</c> = 001 – 366.
    ///   Positions 5-12: A unique identification number generated by the merchant
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Applicable only for CTV for Payouts.</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(12)]
    public string? RetrievalReferenceNumber { get; init; }

    /// <summary>
    /// Visa (maxLength of 15) or MasterCard (maxLength of 40) generated transaction identifier (TID) that is unique for each original authorization and financial request.
    /// * Applicable only for CTV for Payouts.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("accountFundingReferenceId")]
    [MaxLength(40)]
    public string? AccountFundingReferenceId { get; init; }

    /// <summary>
    /// #### Visa Platform Connect
    /// <para>
    /// Contains date and time value indicating scheduled deferred OCT.
    /// </para>
    /// <para>
    /// Format is : 'yyyyMMddHHmm', where
    /// </para>
    /// <para>
    /// 'YYYY' = year
    /// 'MM' = month
    /// 'DD' = day
    /// 'hh' = hour
    /// 'mm' = minutes
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("deferredDateTime")]
    [MaxLength(12)]
    public string? DeferredDateTime { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
