using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation34
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("processor")]
    public Processor? Processor { get; init; }

    /// <summary>
    /// An array of object that contains the list of acquirer response codes &amp; reasons if a transaction is routed to multiple acquirers.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("multiProcessorRouting")]
    public IReadOnlyList<MultiProcessorRouting>? MultiProcessorRouting { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    /// <summary>
    /// Same value as <c>processorInformation.transactionId</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("networkTransactionId")]
    public string? NetworkTransactionId { get; init; }

    /// <summary>
    /// #### Ingenico ePayments
    /// Unique number that CyberSource generates to identify the transaction. You can use this value to identify transactions in the Ingenico ePayments Collections Report, which provides settlement information. Contact customer support for information about the report.
    /// <para>
    /// ### CyberSource through VisaNet
    /// Retrieval request number.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(20)]
    public string? RetrievalReferenceNumber { get; init; }

    /// <summary>
    /// Response ID sent from the processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseId")]
    public string? ResponseId { get; init; }

    /// <summary>
    /// Authorization code. Returned only when the processor returns this value.
    /// <para>
    /// The length of this value depends on your processor.
    /// </para>
    /// <para>
    /// Returned by authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Authorization code that is returned by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### Elavon Encrypted Account Number Program
    /// The returned value is OFFLINE.
    /// </para>
    /// <para>
    /// #### TSYS Acquiring Solutions
    /// The returned value for a successful zero amount authorization is 000000.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("approvalCode")]
    [MaxLength(6)]
    public string? ApprovalCode { get; init; }

    /// <summary>
    /// For most processors, this is the error message sent directly from the bank. Returned only when the processor
    /// returns this value.
    /// <para>
    /// <b>Important</b> Do not use this field to evaluate the result of the authorization.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Response value that is returned by the processor or bank.
    /// <b>Important</b> Do not use this field to evaluate the results of the transaction request.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
    /// </para>
    /// <para>
    /// #### AIBMS
    /// If this value is <c>08</c>, you can accept the transaction if the customer provides you with identification.
    /// </para>
    /// <para>
    /// #### Atos
    /// This value is the response code sent from Atos and it might also include the response code from the bank.
    /// Format: <c>aa,bb</c> with the two values separated by a comma and where:
    /// - <c>aa</c> is the two-digit error message from Atos.
    /// - <c>bb</c> is the optional two-digit error message from the bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// This value is the status code and the error or response code received from the processor separated by a colon.
    /// Format: [status code]:E[error code] or [status code]:R[response code]
    /// Example <c>2:R06</c>
    /// </para>
    /// <para>
    /// #### JCN Gateway
    /// Processor-defined detail error code. The associated response category code is in the <c>processorInformation.responseCategoryCode</c> field.
    /// String (3)
    /// </para>
    /// <para>
    /// #### paypalgateway
    /// Processor generated ID for the itemized detail.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("avs")]
    public Avs? Avs { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cardVerification")]
    public CardVerification2? CardVerification { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("achVerification")]
    public AchVerification? AchVerification { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("electronicVerificationResults")]
    public ElectronicVerificationResults3? ElectronicVerificationResults { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("issuerInformation")]
    public IssuerInformation5? IssuerInformation { get; init; }

    /// <summary>
    /// The event status.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eventStatus")]
    public string? EventStatus { get; init; }

    /// <summary>
    /// This field is returned only for <b>American Express Direct</b> and <b>CyberSource through VisaNet</b>.
    /// Returned by authorization and incremental authorization services.
    /// <para>
    /// #### American Express Direct
    /// </para>
    /// <para>
    /// System trace audit number (STAN). This value identifies the transaction and is useful when investigating a
    /// chargeback dispute.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet
    /// </para>
    /// <para>
    /// System trace number that must be printed on the customer’s receipt.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("systemTraceAuditNumber")]
    [MaxLength(6)]
    public string? SystemTraceAuditNumber { get; init; }

    /// <summary>
    /// Used by Visa only and contains the response source/reason code that identifies the source of the response decision.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCodeSource")]
    [MaxLength(1)]
    public string? ResponseCodeSource { get; init; }

    /// <summary>
    /// Payment Account Reference (PAR) is a non-financial reference assigned to each unique payment account and used to link a payment account to associated network tokens, i.e. the same PAR is returned for PAN-based and tokenized transactions, such as from digital wallets. PAR can be returned in authorisation responses for requests initiated with both real PANs and tokenized PANs. PAR can be used by merchants for fraud detection and regulatory compliance across different channels and digital wallets. PAR allows all participants in the payments chain to have a single, non-sensitive value assigned to a consumer. This value can be used in place of sensitive card holder identification fields, and transmitted across the payments ecosystem to facilitate card holder identification.
    /// <para>
    /// <b>Note</b> On CyberSource through VisaNet, the value for this field corresponds to the following data in the TC 33 capture file:
    /// - Record: CP01 TCR8
    /// - Position: 79-110
    /// - Field: Payment Account Reference
    /// </para>
    /// <para>
    /// The TC 33 Capture file contains information about the purchases and refunds that a merchant submits to CyberSource.
    /// CyberSource through VisaNet creates the TC 33 Capture file at the end of the day and sends it to the merchant’s acquirer,
    /// who uses this information to facilitate end-of-day clearing processing with payment networks.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paymentAccountReferenceNumber")]
    [MaxLength(29)]
    public string? PaymentAccountReferenceNumber { get; init; }

    /// <summary>
    /// This field might contain information about a decline.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(255)]
    public string? ResponseDetails { get; init; }

    /// <summary>
    /// Failure reason returned by the processor in the local language of the processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rawResponseLocal")]
    [MaxLength(255)]
    public string? RawResponseLocal { get; init; }

    /// <summary>
    /// Failure reason returned by the processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rawResponse")]
    [MaxLength(255)]
    public string? RawResponse { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("routing")]
    public Routing? Routing { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
