using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation10
{
    /// <summary>
    /// Authorization code. Returned only when the processor returns this value.
    /// <para>
    /// The length of this value depends on your processor.
    /// </para>
    /// <para>
    /// Returned by authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Authorization code that is returned by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### Elavon Encrypted Account Number Program
    /// The returned value is OFFLINE.
    /// </para>
    /// <para>
    /// #### TSYS Acquiring Solutions
    /// The returned value for a successful zero amount authorization is 000000.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("approvalCode")]
    [MaxLength(6)]
    public string? ApprovalCode { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    /// <summary>
    /// Name of the Japanese acquirer that processed the transaction. Returned only for JCN Gateway.
    /// Please contact the CyberSource Japan Support Group for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("forwardedAcquirerCode")]
    [MaxLength(32)]
    public string? ForwardedAcquirerCode { get; init; }

    /// <summary>
    /// Identifier that was assigned to you by your acquirer. This value must be printed on the receipt.
    /// <para>
    /// #### Returned by
    /// Authorizations and Credits.
    /// </para>
    /// <para>
    /// This reply field is only supported by merchants who have installed client software on their POS terminals and
    /// use these processors:
    /// - American Express Direct
    /// - Credit Mutuel-CIC
    /// - FDC Nashville Global
    /// - OmniPay Direct
    /// - SIX
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantNumber")]
    [MaxLength(15)]
    public string? MerchantNumber { get; init; }

    /// <summary>
    /// For most processors, this is the error message sent directly from the bank. Returned only when the processor
    /// returns this value.
    /// <para>
    /// <b>Important</b> Do not use this field to evaluate the result of the authorization.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Response value that is returned by the processor or bank.
    /// <b>Important</b> Do not use this field to evaluate the results of the transaction request.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
    /// </para>
    /// <para>
    /// #### AIBMS
    /// If this value is <c>08</c>, you can accept the transaction if the customer provides you with identification.
    /// </para>
    /// <para>
    /// #### Atos
    /// This value is the response code sent from Atos and it might also include the response code from the bank.
    /// Format: <c>aa,bb</c> with the two values separated by a comma and where:
    /// - <c>aa</c> is the two-digit error message from Atos.
    /// - <c>bb</c> is the optional two-digit error message from the bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// This value is the status code and the error or response code received from the processor separated by a colon.
    /// Format: [status code]:E[error code] or [status code]:R[response code]
    /// Example <c>2:R06</c>
    /// </para>
    /// <para>
    /// #### JCN Gateway
    /// Processor-defined detail error code. The associated response category code is in the <c>processorInformation.responseCategoryCode</c> field.
    /// String (3)
    /// </para>
    /// <para>
    /// #### paypalgateway
    /// Processor generated ID for the itemized detail.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    /// <summary>
    /// This field is used by Visa only and contains the response source/reason code that identifies the source of the
    /// field 39 response decision. Use this field only for clearing with your acquirer.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseSourceCode")]
    [MaxLength(1)]
    public string? ResponseSourceCode { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("achVerification")]
    public AchVerification? AchVerification { get; init; }

    /// <summary>
    /// Same value as <c>processorInformation.transactionId</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("networkTransactionId")]
    public string? NetworkTransactionId { get; init; }

    /// <summary>
    /// Field contains a settlement date. The date is in mmdd format, where: mm = month and dd = day.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("settlementDate")]
    [MaxLength(4)]
    public string? SettlementDate { get; init; }

    /// <summary>
    /// The date and time when the transaction was last updated, in Internet date and time format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("updateTimeUtc")]
    public string? UpdateTimeUtc { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantAdvice")]
    public MerchantAdvice2? MerchantAdvice { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
