using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation31
{
    /// <summary>
    /// This field is returned by authorization and incremental authorization services.
    /// System trace number that must be printed on the customer’s receipt.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("systemTraceAuditNumber")]
    [MaxLength(6)]
    public string? SystemTraceAuditNumber { get; init; }

    /// <summary>
    /// Issuer-generated approval code for the transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("approvalCode")]
    [MaxLength(6)]
    public string? ApprovalCode { get; init; }

    /// <summary>
    /// Transaction status from the processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). This value can be used to identify a specific transaction when you are discussing the transaction with your processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(15)]
    public string? TransactionId { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("consumerAuthenticationResponse")]
    public ConsumerAuthenticationResponse1? ConsumerAuthenticationResponse { get; init; }

    /// <summary>
    /// This field contains a number that is used with other data elements as a key to identify and track all messages related to a given cardholder transaction; that is, to a given transaction set.
    /// <para>
    /// Recommended format: ydddhhnnnnnn
    /// </para>
    /// <para>
    /// Positions 1-4: The yddd equivalent of the date, where y = 0-9 and ddd = 001 – 366.
    /// Positions 5-12: A unique identification number generated by the merchant or assigned by Cybersource.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(12)]
    public string? RetrievalReferenceNumber { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("avs")]
    public Avs4? Avs { get; init; }

    /// <summary>
    /// This field might contain information about a decline.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(255)]
    public string? ResponseDetails { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customer")]
    public Customer54? Customer { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("electronicVerificationResults")]
    public ElectronicVerificationResults1? ElectronicVerificationResults { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cardVerification")]
    public CardVerification1? CardVerification { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
