using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation15
{
    /// <summary>
    /// For most processors, this is the error message sent directly from the bank. Returned only when the processor
    /// returns this value.
    /// <para>
    /// <b>Important</b> Do not use this field to evaluate the result of the authorization.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Response value that is returned by the processor or bank.
    /// <b>Important</b> Do not use this field to evaluate the results of the transaction request.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
    /// </para>
    /// <para>
    /// #### AIBMS
    /// If this value is <c>08</c>, you can accept the transaction if the customer provides you with identification.
    /// </para>
    /// <para>
    /// #### Atos
    /// This value is the response code sent from Atos and it might also include the response code from the bank.
    /// Format: <c>aa,bb</c> with the two values separated by a comma and where:
    /// - <c>aa</c> is the two-digit error message from Atos.
    /// - <c>bb</c> is the optional two-digit error message from the bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// This value is the status code and the error or response code received from the processor separated by a colon.
    /// Format: [status code]:E[error code] or [status code]:R[response code]
    /// Example <c>2:R06</c>
    /// </para>
    /// <para>
    /// #### JCN Gateway
    /// Processor-defined detail error code. The associated response category code is in the <c>processorInformation.responseCategoryCode</c> field.
    /// String (3)
    /// </para>
    /// <para>
    /// #### paypalgateway
    /// Processor generated ID for the itemized detail.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    /// <summary>
    /// The reason for when the transaction status is Pending or Reversed.
    /// Possible values:
    /// - <c>PAYER_SHIPPING_UNCONFIRMED</c>
    /// - <c>MULTI_CURRENCY</c>
    /// - <c>RISK_REVIEW</c>
    /// - <c>REGULATORY_REVIEW</c>
    /// - <c>VERIFICATION_REQUIRED</c>
    /// - <c>ORDER</c>
    /// - <c>OTHER</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(60)]
    public string? ResponseDetails { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
