using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation24
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sellerProtection")]
    public SellerProtection? SellerProtection { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("avs")]
    public Avs1? Avs { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    /// <summary>
    /// This field might contain information about a decline.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(255)]
    public string? ResponseDetails { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
