using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation35
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("processor")]
    public Processor? Processor { get; init; }

    /// <summary>
    /// Unique ID [codigo] generated by the processor for real-time payments processed directly by the Iugu processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("providerTransactionId")]
    public string? ProviderTransactionId { get; init; }

    /// <summary>
    /// Authorization code. Returned only when the processor returns this value.
    /// <para>
    /// The length of this value depends on your processor.
    /// </para>
    /// <para>
    /// Returned by authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Authorization code that is returned by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### Elavon Encrypted Account Number Program
    /// The returned value is OFFLINE.
    /// </para>
    /// <para>
    /// #### TSYS Acquiring Solutions
    /// The returned value for a successful zero amount authorization is 000000.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("approvalCode")]
    [MaxLength(6)]
    public string? ApprovalCode { get; init; }

    /// <summary>
    /// The event status.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eventStatus")]
    public string? EventStatus { get; init; }

    /// <summary>
    /// #### Ingenico ePayments
    /// Unique number that CyberSource generates to identify the transaction. You can use this value to identify transactions in the Ingenico ePayments Collections Report, which provides settlement information. Contact customer support for information about the report.
    /// <para>
    /// ### CyberSource through VisaNet
    /// Retrieval request number.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(20)]
    public string? RetrievalReferenceNumber { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
