using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation4
{
    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    /// <summary>
    /// For most processors, this is the error message sent directly from the bank. Returned only when the processor
    /// returns this value.
    /// <para>
    /// <b>Important</b> Do not use this field to evaluate the result of the authorization.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Response value that is returned by the processor or bank.
    /// <b>Important</b> Do not use this field to evaluate the results of the transaction request.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
    /// </para>
    /// <para>
    /// #### AIBMS
    /// If this value is <c>08</c>, you can accept the transaction if the customer provides you with identification.
    /// </para>
    /// <para>
    /// #### Atos
    /// This value is the response code sent from Atos and it might also include the response code from the bank.
    /// Format: <c>aa,bb</c> with the two values separated by a comma and where:
    /// - <c>aa</c> is the two-digit error message from Atos.
    /// - <c>bb</c> is the optional two-digit error message from the bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// This value is the status code and the error or response code received from the processor separated by a colon.
    /// Format: [status code]:E[error code] or [status code]:R[response code]
    /// Example <c>2:R06</c>
    /// </para>
    /// <para>
    /// #### JCN Gateway
    /// Processor-defined detail error code. The associated response category code is in the <c>processorInformation.responseCategoryCode</c> field.
    /// String (3)
    /// </para>
    /// <para>
    /// #### paypalgateway
    /// Processor generated ID for the itemized detail.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    /// <summary>
    /// Same value as <c>processorInformation.transactionId</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("networkTransactionId")]
    public string? NetworkTransactionId { get; init; }

    /// <summary>
    /// Processor-defined response category code. The associated detail error code is in the <c>processorInformation.responseCode</c> or <c>issuerInformation.responseCode</c>
    /// field of the service you requested.
    /// <para>
    /// This field is supported only for:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Japanese issuers</description></item>
    ///   <item><description>Domestic transactions in Japan</description></item>
    ///   <item><description>Comercio Latino—processor transaction ID required for troubleshooting</description></item>
    /// </list>
    /// <para>
    /// #### Maximum length for processors
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Comercio Latino: 36</description></item>
    ///   <item><description>All other processors: 3</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCategoryCode")]
    [MaxLength(36)]
    public string? ResponseCategoryCode { get; init; }

    /// <summary>
    /// Name of the Japanese acquirer that processed the transaction. Returned only for JCN Gateway.
    /// Please contact the CyberSource Japan Support Group for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("forwardedAcquirerCode")]
    [MaxLength(32)]
    public string? ForwardedAcquirerCode { get; init; }

    /// <summary>
    /// Mastercard service that was used for the transaction. Mastercard provides this value to CyberSource.
    /// <para>
    /// Possible value:
    ///  - 53: Mastercard card-on-file token service
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet
    /// The value for this field corresponds to the following data in the TC 33 capture file:
    /// - Record: CP01 TCR6
    /// - Position: 133-134
    /// - Field: Mastercard Merchant on-behalf service.
    /// <b>Note</b> This field is returned only for CyberSource through VisaNet.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("masterCardServiceCode")]
    [MaxLength(2)]
    public string? MasterCardServiceCode { get; init; }

    /// <summary>
    /// Result of the Mastercard card-on-file token service. Mastercard provides this value to CyberSource.
    /// <para>
    /// Possible values:
    /// </para>
    /// <para>
    ///  - <c>C</c>: Service completed successfully.
    ///  - <c>F</c>: One of the following:
    ///    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 81 for an authorization or
    ///      authorization reversal.
    ///    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 01 for a tokenized request.
    ///    - Token requestor ID is missing or formatted incorrectly.
    ///  - <c>I</c>: One of the following:
    ///    - Invalid token requestor ID.
    ///    - Suspended or deactivated token.
    ///    - Invalid token (not in mapping table).
    ///  - <c>T</c>: Invalid combination of token requestor ID and token.
    ///  - <c>U</c>: Expired token.
    ///  - <c>W</c>: Primary account number (PAN) listed in electronic warning bulletin.
    /// </para>
    /// <para>
    /// <b>Note</b> This field is returned only for <b>CyberSource through VisaNet</b>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("masterCardServiceReplyCode")]
    [MaxLength(1)]
    public string? MasterCardServiceReplyCode { get; init; }

    /// <summary>
    /// This field might contain information about a decline.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(255)]
    public string? ResponseDetails { get; init; }

    /// <summary>
    /// Processor response to the API request.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("providerResponse")]
    public string? ProviderResponse { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
