using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record ProcessorInformation1
{
    /// <summary>
    /// Flag that specifies the purpose of the authorization.
    /// <para>
    /// Possible values:
    ///  - <c>0</c>: Preauthorization
    ///  - <c>1</c>: Final authorization
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("authIndicator")]
    [MaxLength(1)]
    public string? AuthIndicator { get; init; }

    /// <summary>
    /// Authorization code. Returned only when the processor returns this value.
    /// <para>
    /// The length of this value depends on your processor.
    /// </para>
    /// <para>
    /// Returned by authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Authorization code that is returned by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### Elavon Encrypted Account Number Program
    /// The returned value is OFFLINE.
    /// </para>
    /// <para>
    /// #### TSYS Acquiring Solutions
    /// The returned value for a successful zero amount authorization is 000000.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("approvalCode")]
    [MaxLength(6)]
    public string? ApprovalCode { get; init; }

    /// <summary>
    /// The Scheme reference data is a variable length data element up to a maximum of 56 characters. It may be sent by the acquirer in the
    /// authorisation response message, and by the terminal (unchanged) in subsequent authorisation request messages associated with the same
    /// transaction.
    /// This field is used by Streamline and HSBC UK only, at present.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cardReferenceData")]
    [MaxLength(56)]
    public string? CardReferenceData { get; init; }

    /// <summary>
    /// Network transaction identifier (TID). You can use this value to identify a specific transaction when you are
    /// discussing the transaction with your processor. Not all processors provide this value.
    /// <para>
    /// Returned by the authorization service.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Transaction identifier generated by the processor.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit.
    /// </para>
    /// <para>
    /// #### GPX
    /// Processor transaction ID.
    /// </para>
    /// <para>
    /// #### Cielo
    /// For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet and GPN
    /// For details about this value for CyberSource through VisaNet and GPN, see "processorInformation.networkTransactionId" in <see href="https://developer.cybersource.com/content/dam/docs/cybs/en-us/apifields/reference/all/rest/api-fields.pdf">REST API Fields</see>
    /// </para>
    /// <para>
    /// #### Moneris
    /// This value identifies the transaction on a host system. It contains the following information:
    /// - Terminal used to process the transaction
    /// - Shift during which the transaction took place
    /// - Batch number
    /// - Transaction number within the batch
    /// You must store this value. If you give the customer a receipt, display this value on the receipt.
    /// </para>
    /// <para>
    /// <b>Example</b> For the value
    /// 66012345001069003:
    /// - Terminal ID = 66012345
    /// - Shift number = 001
    /// - Batch number = 069
    /// - Transaction number = 003
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionId")]
    [MaxLength(255)]
    public string? TransactionId { get; init; }

    /// <summary>
    /// Same value as <c>processorInformation.transactionId</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("networkTransactionId")]
    public string? NetworkTransactionId { get; init; }

    /// <summary>
    /// For most processors, this is the error message sent directly from the bank. Returned only when the processor
    /// returns this value.
    /// <para>
    /// <b>Important</b> Do not use this field to evaluate the result of the authorization.
    /// </para>
    /// <para>
    /// #### PIN debit
    /// Response value that is returned by the processor or bank.
    /// <b>Important</b> Do not use this field to evaluate the results of the transaction request.
    /// </para>
    /// <para>
    /// Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.
    /// </para>
    /// <para>
    /// #### AIBMS
    /// If this value is <c>08</c>, you can accept the transaction if the customer provides you with identification.
    /// </para>
    /// <para>
    /// #### Atos
    /// This value is the response code sent from Atos and it might also include the response code from the bank.
    /// Format: <c>aa,bb</c> with the two values separated by a comma and where:
    /// - <c>aa</c> is the two-digit error message from Atos.
    /// - <c>bb</c> is the optional two-digit error message from the bank.
    /// </para>
    /// <para>
    /// #### Comercio Latino
    /// This value is the status code and the error or response code received from the processor separated by a colon.
    /// Format: [status code]:E[error code] or [status code]:R[response code]
    /// Example <c>2:R06</c>
    /// </para>
    /// <para>
    /// #### JCN Gateway
    /// Processor-defined detail error code. The associated response category code is in the <c>processorInformation.responseCategoryCode</c> field.
    /// String (3)
    /// </para>
    /// <para>
    /// #### paypalgateway
    /// Processor generated ID for the itemized detail.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCode")]
    [MaxLength(10)]
    public string? ResponseCode { get; init; }

    /// <summary>
    /// Used by Visa only and contains the response source/reason code that identifies the source of the response decision.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCodeSource")]
    [MaxLength(1)]
    public string? ResponseCodeSource { get; init; }

    /// <summary>
    /// This field might contain information about a decline.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseDetails")]
    [MaxLength(255)]
    public string? ResponseDetails { get; init; }

    /// <summary>
    /// Processor-defined response category code. The associated detail error code is in the <c>processorInformation.responseCode</c> or <c>issuerInformation.responseCode</c>
    /// field of the service you requested.
    /// <para>
    /// This field is supported only for:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Japanese issuers</description></item>
    ///   <item><description>Domestic transactions in Japan</description></item>
    ///   <item><description>Comercio Latino—processor transaction ID required for troubleshooting</description></item>
    /// </list>
    /// <para>
    /// #### Maximum length for processors
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Comercio Latino: 36</description></item>
    ///   <item><description>All other processors: 3</description></item>
    /// </list>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseCategoryCode")]
    [MaxLength(36)]
    public string? ResponseCategoryCode { get; init; }

    /// <summary>
    /// This field is used by Visa only and contains the response source/reason code that identifies the source of the response decision.
    /// Use this field only for clearing with your acquirer.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("responseSourceCode")]
    [MaxLength(1)]
    public string? ResponseSourceCode { get; init; }

    /// <summary>
    /// Name of the Japanese acquirer that processed the transaction. Returned only for JCN Gateway.
    /// Please contact the CyberSource Japan Support Group for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("forwardedAcquirerCode")]
    [MaxLength(32)]
    public string? ForwardedAcquirerCode { get; init; }

    /// <summary>
    /// Field contains a settlement date. The date is in mmdd format, where: mm = month and dd = day.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("settlementDate")]
    [MaxLength(4)]
    public string? SettlementDate { get; init; }

    /// <summary>
    /// This field serves as a unique identifier for initial and subsequent recurring transactions, specific to the payment brand, and is crucial for transaction tracking and recurrence management. Not all processors provide this value.
    /// Returned by the authorization service.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sequenceNumber")]
    [MaxLength(50)]
    public string? SequenceNumber { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("avs")]
    public Avs? Avs { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cardVerification")]
    public CardVerification1? CardVerification { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantAdvice")]
    public MerchantAdvice? MerchantAdvice { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("electronicVerificationResults")]
    public ElectronicVerificationResults? ElectronicVerificationResults { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("achVerification")]
    public AchVerification? AchVerification { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customer")]
    public Customer2? Customer { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("consumerAuthenticationResponse")]
    public ConsumerAuthenticationResponse? ConsumerAuthenticationResponse { get; init; }

    /// <summary>
    /// This field is returned only for <b>American Express Direct</b> and <b>CyberSource through VisaNet</b>.
    /// Returned by authorization and incremental authorization services.
    /// <para>
    /// #### American Express Direct
    /// </para>
    /// <para>
    /// System trace audit number (STAN). This value identifies the transaction and is useful when investigating a
    /// chargeback dispute.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet
    /// </para>
    /// <para>
    /// System trace number that must be printed on the customer’s receipt.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("systemTraceAuditNumber")]
    [MaxLength(6)]
    public string? SystemTraceAuditNumber { get; init; }

    /// <summary>
    /// Payment Account Reference (PAR) is a non-financial reference assigned to each unique payment account and used to link a payment account to associated network tokens, i.e. the same PAR is returned for PAN-based and tokenized transactions, such as from digital wallets. PAR can be returned in authorisation responses for requests initiated with both real PANs and tokenized PANs. PAR can be used by merchants for fraud detection and regulatory compliance across different channels and digital wallets. PAR allows all participants in the payments chain to have a single, non-sensitive value assigned to a consumer. This value can be used in place of sensitive card holder identification fields, and transmitted across the payments ecosystem to facilitate card holder identification.
    /// <para>
    /// <b>Note</b> On CyberSource through VisaNet, the value for this field corresponds to the following data in the TC 33 capture file:
    /// - Record: CP01 TCR8
    /// - Position: 79-110
    /// - Field: Payment Account Reference
    /// </para>
    /// <para>
    /// The TC 33 Capture file contains information about the purchases and refunds that a merchant submits to CyberSource.
    /// CyberSource through VisaNet creates the TC 33 Capture file at the end of the day and sends it to the merchant’s acquirer,
    /// who uses this information to facilitate end-of-day clearing processing with payment networks.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paymentAccountReferenceNumber")]
    [MaxLength(29)]
    public string? PaymentAccountReferenceNumber { get; init; }

    /// <summary>
    /// Transaction integrity classification provided by Mastercard. This value specifies Mastercard’s evaluation of
    /// the transaction’s safety and security. This field is returned only for <b>CyberSource through VisaNet</b>.
    /// <para>
    /// For card-present transactions, possible values:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>A1</c>: EMV or token in a secure, trusted environment</description></item>
    ///   <item><description><c>B1</c>: EMV or chip equivalent</description></item>
    ///   <item><description><c>C1</c>: Magnetic stripe</description></item>
    ///   <item><description><c>E1</c>: Key entered</description></item>
    ///   <item><description><c>U0</c>: Unclassified</description></item>
    /// </list>
    /// <para>
    /// For card-not-present transactions, possible values:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>A2</c>: Digital transactions</description></item>
    ///   <item><description><c>B2</c>: Authenticated checkout</description></item>
    ///   <item><description><c>C2</c>: Transaction validation</description></item>
    ///   <item><description><c>D2</c>: Enhanced data</description></item>
    ///   <item><description><c>E2</c>: Generic messaging</description></item>
    ///   <item><description><c>U0</c>: Unclassified</description></item>
    /// </list>
    /// <para>
    /// For information about these values, contact Mastercard or your acquirer.
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet
    /// </para>
    /// <para>
    /// The value for this field corresponds to the following data in the TC 33 capture file,&lt;sup&gt;1&lt;/sup&gt;:
    /// - Record: CP01 TCR6
    /// - Position: 136-137
    /// - Field: Mastercard Transaction Integrity Classification
    /// </para>
    /// <para>
    /// &lt;sup&gt;1&lt;/sup&gt; The TC 33 Capture file contains information about the purchases and refunds that a merchant submits to CyberSource.
    /// CyberSource through VisaNet creates the TC 33 Capture file at the end of the day and sends it to the merchant’s acquirer, who uses
    /// this information to facilitate end-of-day clearing processing with payment networks.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionIntegrityCode")]
    [MaxLength(2)]
    public string? TransactionIntegrityCode { get; init; }

    /// <summary>
    /// Referral response number for a verbal authorization with FDMS Nashville when using an American Express card.
    /// Give this number to American Express when you call them for the verbal authorization.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("amexVerbalAuthReferenceNumber")]
    [MaxLength(6)]
    public string? AmexVerbalAuthReferenceNumber { get; init; }

    /// <summary>
    /// Mastercard service that was used for the transaction. Mastercard provides this value to CyberSource.
    /// <para>
    /// Possible value:
    ///  - 53: Mastercard card-on-file token service
    /// </para>
    /// <para>
    /// #### CyberSource through VisaNet
    /// The value for this field corresponds to the following data in the TC 33 capture file:
    /// - Record: CP01 TCR6
    /// - Position: 133-134
    /// - Field: Mastercard Merchant on-behalf service.
    /// <b>Note</b> This field is returned only for CyberSource through VisaNet.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("masterCardServiceCode")]
    [MaxLength(2)]
    public string? MasterCardServiceCode { get; init; }

    /// <summary>
    /// Result of the Mastercard card-on-file token service. Mastercard provides this value to CyberSource.
    /// <para>
    /// Possible values:
    /// </para>
    /// <para>
    ///  - <c>C</c>: Service completed successfully.
    ///  - <c>F</c>: One of the following:
    ///    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 81 for an authorization or
    ///      authorization reversal.
    ///    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 01 for a tokenized request.
    ///    - Token requestor ID is missing or formatted incorrectly.
    ///  - <c>I</c>: One of the following:
    ///    - Invalid token requestor ID.
    ///    - Suspended or deactivated token.
    ///    - Invalid token (not in mapping table).
    ///  - <c>T</c>: Invalid combination of token requestor ID and token.
    ///  - <c>U</c>: Expired token.
    ///  - <c>W</c>: Primary account number (PAN) listed in electronic warning bulletin.
    /// </para>
    /// <para>
    /// <b>Note</b> This field is returned only for <b>CyberSource through VisaNet</b>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("masterCardServiceReplyCode")]
    [MaxLength(1)]
    public string? MasterCardServiceReplyCode { get; init; }

    /// <summary>
    /// Type of authentication for which the transaction qualifies as determined by the Mastercard authentication
    /// service, which confirms the identity of the cardholder. Mastercard provides this value to CyberSource.
    /// <para>
    /// Possible values:
    /// </para>
    /// <list type="bullet">
    ///   <item><description><c>1</c>: Transaction qualifies for Mastercard authentication type 1.</description></item>
    ///   <item><description><c>2</c>: Transaction qualifies for Mastercard authentication type 2.</description></item>
    /// </list>
    /// <para>
    /// #### CyberSource through VisaNet
    /// The value for this field corresponds to the following data in the TC 33 capture file:
    /// - Record: CP01 TCR6
    /// - Position: 132
    /// - Field: Mastercard Member Defined service.
    /// <b>Note</b> This field is returned only for CyberSource through VisaNet.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("masterCardAuthenticationType")]
    [MaxLength(1)]
    public string? MasterCardAuthenticationType { get; init; }

    /// <summary>
    /// Name of the Processor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    [MaxLength(30)]
    public string? Name { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("routing")]
    public Routing? Routing { get; init; }

    /// <summary>
    /// Identifier that was assigned to you by your acquirer. This value must be printed on the receipt.
    /// <para>
    /// #### Returned by
    /// Authorizations and Credits.
    /// </para>
    /// <para>
    /// This reply field is only supported by merchants who have installed client software on their POS terminals and
    /// use these processors:
    /// - American Express Direct
    /// - Credit Mutuel-CIC
    /// - FDC Nashville Global
    /// - OmniPay Direct
    /// - SIX
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantNumber")]
    [MaxLength(15)]
    public string? MerchantNumber { get; init; }

    /// <summary>
    /// #### Ingenico ePayments
    /// Unique number that CyberSource generates to identify the transaction. You can use this value to identify transactions in the Ingenico ePayments Collections Report, which provides settlement information. Contact customer support for information about the report.
    /// <para>
    /// ### CyberSource through VisaNet
    /// Retrieval request number.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("retrievalReferenceNumber")]
    [MaxLength(20)]
    public string? RetrievalReferenceNumber { get; init; }

    /// <summary>
    /// Direct the customer to this URL to complete the payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paymentUrl")]
    [MaxLength(2048)]
    public string? PaymentUrl { get; init; }

    /// <summary>
    /// The redirect URL for forwarding the consumer to complete page.  This redirect needed by PSP to track browser information of consumer.
    /// PSP then redirect consumer to merchant success URL.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("completeUrl")]
    [MaxLength(2048)]
    public string? CompleteUrl { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("signature")]
    public string? Signature { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("publicKey")]
    public string? PublicKey { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sellerProtection")]
    public ProcessorInformationSellerProtection? SellerProtection { get; init; }

    /// <summary>
    /// The date on which the transaction expires and payment cannot be made.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transactionExpiryDate")]
    [MaxLength(8)]
    public string? TransactionExpiryDate { get; init; }

    /// <summary>
    /// For merchants to declare customs
    /// Customs declaration service URL.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customUrl")]
    public string? CustomUrl { get; init; }

    /// <summary>
    /// Unique id assigned to a merchant by the APM and not PSP
    /// The merchant ID, as boarded with Alipay
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("schemeAssignedId")]
    [MaxLength(150)]
    public string? SchemeAssignedId { get; init; }

    /// <summary>
    /// The QR code value. Convert this value into an image and send it to the POS terminal to be displayed. The terminal can also perform the conversion.
    /// The value is a URL like in the example below:
    /// https://qr.alipay.com/pmxabcka1ts5grar12.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("deviceUrl")]
    [MaxLength(50)]
    public string? DeviceUrl { get; init; }

    /// <summary>
    /// The funds are released to the merchant immediately.
    /// INSTANT	The funds are released to the merchant immediately.
    /// DELAYED	The funds are held for a finite number of days. The actual duration depends on the region and type of integration. You can release the funds through a referenced payout. Otherwise, the funds disbursed automatically after the specified duration.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disbursementMode")]
    public string? DisbursementMode { get; init; }

    /// <summary>
    /// The date and time when the transaction was last updated, in Internet date and time format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("updateTimeUtc")]
    public string? UpdateTimeUtc { get; init; }

    /// <summary>
    /// The date and time when the authorized payment expires, in Internet date and time format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("expirationTimeUtc")]
    public string? ExpirationTimeUtc { get; init; }

    /// <summary>
    /// The id of the order
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("orderId")]
    public string? OrderId { get; init; }

    /// <summary>
    /// The order status.
    /// Possible values:
    /// - <c>CREATED</c>
    /// - <c>VOIDED</c>
    /// - <c>COMPLETED</c>
    /// - <c>PAYER_ACTION_REQUIRED</c>
    /// - <c>STEP_UP_REQUIRED</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("orderStatus")]
    [MaxLength(255)]
    public string? OrderStatus { get; init; }

    /// <summary>
    /// Mastercard is introducing the Merchant Risk Predict Service in the middle East/Africa Region.
    /// A newly launched service comprised of seven independent artificial intelligence (AI)-powered scores intended to augment existing merchant risk management practices.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchantRiskPrediction")]
    [MaxLength(150)]
    public string? MerchantRiskPrediction { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("network")]
    public Network? Network { get; init; }

    /// <summary>
    /// Merchant Commercial Enhanced Data Program (CEDP) verified indicator received in authorization response messages for U.S. domestic transactions containing a credential for the commercial credit products.
    /// <para>
    /// This field flows in ISO field 34, DSID 02 tag DA, in AN, EBCDIC format.
    /// </para>
    /// <para>
    /// Possible values:
    /// - <c>Y</c>: Merchant CEDP verified
    /// </para>
    /// <para>
    /// This field is for internal processing only (TC33A usage) and is not sent back to the merchant.
    /// </para>
    /// <para>
    /// #### Used by
    /// <b>Authorization Response</b>
    /// Response field only.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cedpVerifiedIndicator")]
    [MaxLength(1)]
    public string? CedpVerifiedIndicator { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
