using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record SenderInformation3
{
    /// <summary>
    /// Reference number generated by you that uniquely identifies the sender.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("referenceNumber")]
    [MaxLength(19)]
    public string? ReferenceNumber { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("account")]
    public Account16? Account { get; init; }

    /// <summary>
    /// First name of the sender.
    /// This field is applicable for AFT and OCT transactions.
    /// <para>
    /// Only alpha numeric values are supported.Special characters not in the standard ASCII character set, are not supported and will be stripped before being sent to the processor.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("firstName")]
    [MaxLength(30)]
    public string? FirstName { get; init; }

    /// <summary>
    /// Recipient middle initial (Optional).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("middleInitial")]
    [MaxLength(1)]
    public string? MiddleInitial { get; init; }

    /// <summary>
    /// Middle name of the sender.
    /// This field is applicable for AFT and OCT transactions.
    /// <para>
    /// Only alpha numeric values are supported. Special characters not in the standard ASCII character set, are not supported and will be stripped before being sent to sent to the processor.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("middleName")]
    [MaxLength(30)]
    public string? MiddleName { get; init; }

    /// <summary>
    /// Last name of the sender.
    /// This field is applicable for AFT and OCT transactions.
    /// <para>
    /// Only alpha numeric values are supported. Special characters not in the standard ASCII character set, are not supported and will be stripped before being sent to sent to the processor.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("lastName")]
    [MaxLength(30)]
    public string? LastName { get; init; }

    /// <summary>
    /// Name of sender.
    /// <para>
    /// <b>Funds Disbursement</b>
    /// </para>
    /// <para>
    /// This value is the name of the originator sending the funds disbursement.
    /// * CTV, Paymentech (30)
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    [MaxLength(24)]
    public string? Name { get; init; }

    /// <summary>
    /// Street address of sender.
    /// <para>
    /// <b>Funds Disbursement</b>
    /// </para>
    /// <para>
    /// This value is the address of the originator sending the funds disbursement.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("address1")]
    [MaxLength(50)]
    public string? Address1 { get; init; }

    /// <summary>
    /// City of sender.
    /// <para>
    /// <b>Funds Disbursement</b>
    /// </para>
    /// <para>
    /// This value is the city of the originator sending the funds disbursement.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("locality")]
    [MaxLength(25)]
    public string? Locality { get; init; }

    /// <summary>
    /// Sender’s state. Use the <see href="https://developer.cybersource.com/library/documentation/sbc/quickref/states_and_provinces.pdf">State, Province, and Territory Codes for the United States and Canada</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("administrativeArea")]
    [MaxLength(2)]
    public string? AdministrativeArea { get; init; }

    /// <summary>
    /// Country of sender. Use the <see href="https://developer.cybersource.com/library/documentation/sbc/quickref/countries_alpha_list.pdf">ISO Standard Country Codes</see>.
    /// * CTV (3)
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("countryCode")]
    [MaxLength(2)]
    public string? CountryCode { get; init; }

    /// <summary>
    /// Sender’s postal code. Required only for FDCCompass.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("postalCode")]
    [MaxLength(10)]
    public string? PostalCode { get; init; }

    /// <summary>
    /// Sender’s phone number. Required only for FDCCompass.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("phoneNumber")]
    [MaxLength(20)]
    public string? PhoneNumber { get; init; }

    /// <summary>
    /// Sender’s date of birth in YYYYMMDD format. Required only for FDCCompass.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dateOfBirth")]
    [StringLength(8, MinimumLength = 8)]
    public string? DateOfBirth { get; init; }

    /// <summary>
    /// Customer's government-assigned tax identification number.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("vatRegistrationNumber")]
    [MaxLength(13)]
    public string? VatRegistrationNumber { get; init; }

    /// <summary>
    /// #### Visa Platform Connect
    /// This tag will contain the type of sender identification.
    /// The valid values are:
    /// • BTHD (Date of birth)
    /// • CUID (Customer identification (unspecified))
    /// • NTID (National identification)
    /// • PASN (Passport number)
    /// • DRLN (Driver license)
    /// • TXIN (Tax identification)
    /// • CPNY (Company registration number)
    /// • PRXY (Proxy identification)
    /// • SSNB (Social security number)
    /// • ARNB (Alien registration number)
    /// • LAWE (Law enforcement identification)
    /// • MILI (Military identification)
    /// • TRVL (Travel identification (non-passport))
    /// • EMAL (Email)
    /// • PHON (Phone number)
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("personalIdType")]
    [MaxLength(4)]
    public string? PersonalIdType { get; init; }

    /// <summary>
    /// #### Visa Platform Connect
    /// This tag will denote whether the tax ID is a business or individual tax ID when personal ID Type contains the value of TXIN (Tax identification).
    /// <para>
    /// The valid values are:
    /// • B (Business)
    /// • I (Individual)
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    [MaxLength(1)]
    public string? Type { get; init; }

    /// <summary>
    /// #### Visa Platform Connect
    /// This tag will contain an acquirer-populated value associated with the API : senderInformation.personalIdType which will identify the personal ID type of the sender.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("identificationNumber")]
    [MaxLength(255)]
    public string? IdentificationNumber { get; init; }

    /// <summary>
    /// Sender's alias name.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("aliasName")]
    [MaxLength(50)]
    public string? AliasName { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
