using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using CyberSourceMergedSpec.Core.Models;

namespace CyberSourceMergedSpec.Models;

public record Tmsv2TokenizedCard
{
    /// <summary>
    /// The Id of the Tokenized Card.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The type.
    /// Possible Values:
    /// - tokenizedCard
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("object")]
    public string? Object { get; init; }

    /// <summary>
    /// Source of the card details.
    /// Possible Values:
    /// - ONFILE
    /// - TOKEN
    /// - ISSUER
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>
    /// State of the network token or network token provision.
    /// Possible Values:
    ///   - ACTIVE : Network token is active.
    ///   - SUSPENDED : Network token is suspended. This state can change back to ACTIVE.
    ///   - DELETED : This is a final state for a network token instance.
    ///   - UNPROVISIONED : A previous network token.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("state")]
    public string? State { get; init; }

    /// <summary>
    /// Unique id to identify this PAN/ enrollment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("enrollmentId")]
    public string? EnrollmentId { get; init; }

    /// <summary>
    /// Unique ID for netwrok token.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("tokenReferenceId")]
    public string? TokenReferenceId { get; init; }

    /// <summary>
    /// The token requestor's network token for the provided PAN and consumer Id, if available.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("number")]
    public string? Number { get; init; }

    /// <summary>
    /// Two-digit month in which the network token expires.
    /// Format: <c>MM</c>.
    /// Possible Values: <c>01</c> through <c>12</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("expirationMonth")]
    public string? ExpirationMonth { get; init; }

    /// <summary>
    /// Four-digit year in which the network token expires.
    /// Format: <c>YYYY</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("expirationYear")]
    public string? ExpirationYear { get; init; }

    /// <summary>
    /// The type of card (Card Network).
    /// Possible Values:
    /// - visa
    /// - mastercard
    /// - americanexpress
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// Indicates the reason why the network token provision request failed.
    /// Possible Values:
    /// - INVALID_REQUEST : The network token provision request contained invalid data.
    /// - CARD_VERIFICATION_FAILED : The network token provision request contained data that could not be verified.
    /// - CARD_NOT_ELIGIBLE : Card can currently not be used with issuer for tokenization.
    /// - CARD_NOT_ALLOWED : Card can currently not be used with card association for tokenization.
    /// - DECLINED : Card can currently not be used with issuer for tokenization.
    /// - SERVICE_UNAVAILABLE : The network token service was unavailable or timed out.
    /// - SYSTEM_ERROR : An unexpected error occurred with network token service, check configuration.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

    /// <summary>
    /// Value generated by the card association to be used alongside the network token for processing a payment.
    /// This field is returned by default for Visa and Mastercard network tokens.
    /// It can also be explicitly requested using paymentCredentialType: CRYPTOGRAM.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cryptogram")]
    public string? Cryptogram { get; init; }

    /// <summary>
    /// Dynamic number generated by the card association to be used alongside the network token for processing a payment.
    /// - For American Express: Dynamic Card Secure Code (DCSC) returned by default.
    /// - For Visa: DTVV cryptogram when explicitly requested using paymentCredentialType: SECURITY_CODE.
    /// It can also be explicitly requested using paymentCredentialType: SECURITY_CODE.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("securityCode")]
    public string? SecurityCode { get; init; }

    /// <summary>
    /// Raw Electronic Commerce Indicator provided by the card association with the result of the cardholder authentication.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("eci")]
    public string? Eci { get; init; }

    /// <summary>
    /// 11-digit identifier that uniquely identifies the Token Requestor.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("requestorId")]
    [MaxLength(11)]
    public string? RequestorId { get; init; }

    /// <summary>
    /// Payment account reference.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paymentAccountReference")]
    public string? PaymentAccountReference { get; init; }

    /// <summary>
    /// A sequence counter used as part of the input to the TAVV cryptogram and it is incremented for each cryptogram generation.
    /// This field is only returned for Visa network tokens.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applicationTransactionCounter")]
    public string? ApplicationTransactionCounter { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card")]
    public Card15? Card { get; init; }

    /// <summary>
    /// Verification results returned by the issuer during the provisioning when Security Code or Billing Address data is provided on the request.
    /// Supported only for VTS tokens.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("verificationResults")]
    public VerificationResults? VerificationResults { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("metadata")]
    public Metadata2? Metadata { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
